#define LINUX 
#define PVR_BUILD_DIR "omap4430_android"
#define PVR_BUILD_TYPE "debug"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SGXCORE 544
#define SGX544 
#define SUPPORT_SGX544 
#define SUPPORT_SGX 
#define SGX_CORE_REV 112
#define TRANSFER_QUEUE 
#define PVR_SECURE_HANDLES 
#define DISPLAY_CONTROLLER omaplfb
#define PVR_LINUX_MEM_AREA_POOL_MAX_PAGES 10800
#define PVR_LINUX_MEM_AREA_USE_VMAP 
#define PVR_LINUX_MEM_AREA_POOL_ALLOW_SHRINK 
#define DEBUG 
#define DEBUG_LINUX_MEMORY_ALLOCATIONS 
#define DEBUG_LINUX_MEM_AREAS 
#define DEBUG_LINUX_MMAP_AREAS 
#define DEBUG_BRIDGE_KM 
#define SUPPORT_PERCONTEXT_PB 
#define SUPPORT_HW_RECOVERY 
#define SUPPORT_ACTIVE_POWER_MANAGEMENT 
#define SUPPORT_SGX_HWPERF 
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING 
#define SUPPORT_MEMINFO_IDS 
#define SUPPORT_SGX_NEW_STATUS_VALS 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define PVRSRV_USSE_EDM_STATUS_DEBUG 
#define SGX_DISABLE_VISTEST_SUPPORT 
#define SYS_USING_INTERRUPTS 
#define PVRSRV_NEW_PVR_DPF 
#define PVRSRV_NEED_PVR_DPF 
#define PVRSRV_NEED_PVR_ASSERT 
#define PVRSRV_NEED_PVR_TRACE 
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define SGX_DYNAMIC_TIMING_INFO 
#define SYS_CUSTOM_POWERLOCK_WRAP 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define LDM_PLATFORM 
#define PVR_LDM_PLATFORM_PRE_REGISTERED 
#define PVR_LDM_PLATFORM_PRE_REGISTERED_DEV "pvrsrvkm"
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define PVRSRV_DUMP_MK_TRACE 
#define SUPPORT_LARGE_GENERAL_HEAP 
#define CONFIG_PVR_PROC_FS 
#define ANDROID 
#define PVR_NO_OMAP_TIMER 
#define SYS_OMAP4_HAS_DVFS_FRAMEWORK 
#define SUPPORT_DC_CMDCOMPLETE_WHEN_NO_LONGER_DISPLAYED 
